config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/view'

  root 'restaurants#index'

  resources :sessions, only:[:create, :new, :destroy]
  resources :customers, except: [:index]
  resources :restaurants do #,only:[:show, :index] do
    resources :reservations
  end
  resources :categories
  # , only:[:index, :show]

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_secure_password

  validates :name, :email, :password_confirmation, presence: true
  validates :name, length: {minimum: 2}
  validates :password,
    length: {in: 4..20, incorrect_pw_length: "password must be 4 to 20 characters"}
  validate :validation_list;

  has_many :reservations, dependent: :destroy
  has_many :restaurants, through: :reservations

  def validation_list
    if self.name == nil || self.email == nil || self.password == nil
      return
    end
    numpresent = self.password.match(/\d/)? 1:0
    if numpresent == 0
      errors.add(:password, 'requires at least 1 digit')
    end
    spacepresent = self.password.match(/\s/)? 1:0
    if spacepresent == 1
      errors.add(:password, 'spaces are invalid. please use other character')
    end
    emailaddress = self.email.match(/\S+@\S+.\S/)? 1:0
    if emailaddress == 0
      errors.add(:email, "check format (requires @, and domain name) #{emailaddress}, #{:email}, #{self.email}")
    end
  end


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
        redirect_to new_session_path
    else
        render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update_attributes(customer_params)
      redirect_to customer_path(current_customer), notice: "Customer profile successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
        session[:customer_id] = nil
    redirect_to restaurants_path, notice: "Profile successfully deleted. We hope you join us again some day!"
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class = 'flash_notices'>
  <% if @customer.errors.any? %>
    <% @customer.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
  <% end %>
</div>

<div class="sign_up_container">
  <h1>Sign up</h1>
  <%= form_for @customer do |f| %>
    <div>
      <%= f.label :name, "Name"%>
    </div>
    <div>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :email, "E-mail"%>
    </div>
    <div>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :password, "Password *"%>
    </div>
    <div>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation, "Password Confirmation" %>
    </div>
    <div>
      <%= f.password_field :password_confirmation %>
    </div>

    <div>
      <%= f.submit 'Sign Up', class:'form_button' %>
    </div>
  <% end %>
</div>

*Note: Password must contain min. 4 characters and 1 number 

app/views/customers/edit.html.erb
<h1>Update Profile!</h1>
<p> </p>


<%=render @customer %>

app/views/customers/new.html.erb
<%= render @customer %>

app/views/customers/show.html.erb
<div class="profile_container">
<h1 class="profile_title"> My Profile</h1>


<div class="update_profile">
  <%= link_to 'Update profile ', edit_customer_path(current_customer) %>
</div>
<div class = 'divider'> &nbsp|&nbsp</div>
<div class="delete_profile">
  <%= link_to 'Delete profile ', current_customer, method: :delete, data: {confirm: "Are you sure you want to leave us?"} %>
</div>

  <div class="profile_name">
    <span class="prof_label">Name:</span> <%= current_customer.name %>
  </div>

  <div>
      <span class="prof_label">Email:</span><%= current_customer.email %>
  </div>

<div>
  <span class="prof_label">Reservations:</span>
  <% current_customer.reservations.each do |reservation| %>
    <ul>
      <li> <%= reservation.restaurant.name %> <%= reservation.date %> <%= chop_time(reservation.time) %>
      </li><%= link_to 'View Reservation Details', restaurant_reservation_path(restaurant_id: reservation.restaurant_id, id: reservation.id) %>
    </ul>
  <% end%>
</div>
</div>