config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/view'

  root 'restaurants#index'

  resources :sessions, only:[:create, :new, :destroy]
  resources :customers, except: [:index]
  resources :restaurants do #,only:[:show, :index] do
    resources :reservations
  end
  resources :categories
  # , only:[:index, :show]

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reservations
  has_many :customers, through: :reservations
  belongs_to :category

  validates :name, presence: true
  validates :img_link, presence: true

  def availability(party_size, time)
     if party_size != nil && time != nil
       current_capacity(time) - party_size
     end
   end

   def time_range(restaurant)
     form_time_range = []
     time_option = restaurant.opening
     while time_option < restaurant.closing
      form_time_range << time_option
       time_option = time_option+1.hour
     end
     form_time_range
   end

   def time_range_show(form_time)
     time_options = form_time.map {|time| time.strftime("%H:%M%p") }
   end

# helper_method :time_range
   private
   def current_capacity(time)
     if self.reservations.empty?
       capacity
     else
     capacity - reserved_capacity(time)
    end
   end

   def reserved_capacity(time)
     self.reservations.where(time: time.beginning_of_hour..time.end_of_hour).sum(:party_size)
   end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :load_restaurant, except: [:create, :index, :new]


  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new(restaurant_id: params[:id] )
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def update
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurants_path
    else
      render :edit
    end
  end
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def load_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :img_link, :opening, :closing, :capacity, :category_id)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper



end

app/views/restaurants/_restaurant.html.erb
<div class = 'flash_notices'>
  <% if @restaurant.errors.any? %>
    <% @restaurant.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
    <% end %>
  <% end %>
</div>

<div>
  <%= form_for @restaurant do |f| %>
    <div>
      <%= f.label :name, "Name"%>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :img_link, "Image Link" %>
      <%= f.text_field :img_link %>
    </div>

    <div>
      <%= f.label :opening, "Opening Time"%>
      <%= f.time_field :opening %>
    </div>

    <div>
      <%= f.label :closing, "Closing Time"%>
      <%= f.time_field :closing %>
    </div>

    <div>
      <%= f.label :capacity, "Capacity" %>
      <%= f.text_field :capacity %>
    </div>
    <div>

      <%= f.label :category, "Categories"%>
      <%= f.collection_select(:category_id, Category.all, :id, :name) %>

    </div>

    <div>
      <%= f.submit 'Go! ' %>
    </div>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<h1> Update a Restaurant </h1>

<%= render @restaurant %>

app/views/restaurants/index.html.erb
<section id="carousel_banner">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
  <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
       <img src="https://drscdn.500px.org/photo/original/store/139863569/m%3D900_k%3D2_b%3D2_dpi%3D300_attachment%3D1_tags%3D1/5b55eaaae444ba161b589ef7c2ef6a88" width="1400px">
       <div class="carousel-caption">
        <p class="carousel_desc">Book Tables With Ease.</p>
      <!-- </div> -->
      </div>
    </div>

    <div class="item">
      <img src="https://drscdn.500px.org/photo/original/store/124067803/m%3D900_k%3D2_b%3D2_dpi%3D300_attachment%3D1_tags%3D1/e96cc182b153a98f74deaade7e3b7f7f" width="1400px">
      <div class="carousel-caption">
       <p class="carousel_desc">Discover New Local Restaurants with just one click.</p>
     </div>
    </div>

    <div class="item">
      <img src="https://drscdn.500px.org/photo/129497793/q%3D85_w%3D560_s%3D1/c96349379d1467d1c54555a34224dd11" width="1400px">
      <div class="carousel-caption">
       <p class="carousel_desc">Have a Craving? We got you covered!</p>
     </div>
    </div>


  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</section>

<section id="restaurants_container">
  <% if session[:account_type] == 'admin' %>
    <%= link_to 'Add a Restaurant', new_restaurant_path, class:'add_resto' %>
  <%end%>

  <h2 class="rest_title">Discover New Restaurants</h2>
  <p class="rest_desc">Treat Your Tastebuds. Eat anywhere, at any time. </p>

<div id = 'search options'>
  <%= link_to 'Search by Category', categories_path %>
</div>

  <% @restaurants.each do |restaurant| %>
    <div class="restaurant">
      <div class="restaurant_image">
        <%= link_to image_tag(restaurant.img_link),restaurant_path(restaurant)%>
      </div>
      <p class="restaurant_name"><%= link_to(restaurant.name, restaurant_path(restaurant))%></p>
      <p class="restaurant_category"><%=restaurant.category.name%></p>
    </div>
  <% end %>

</section>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<%= render @restaurant %>

app/views/restaurants/show.html.erb
<div class= "reservation_container">
    <h1 class="reserve_title"> Make a Reservation </h1>


    <div class = 'flash_notices'>
      <% if @reservation.errors.any? %>
        <% @reservation.errors.full_messages.each do |msg| %>
        <ul>
          <li><%= msg %></li>
        </ul>
        <% end %>
      <% end %>
    </div>

<% if current_customer %>
  <%= form_for [@restaurant, @reservation] do |f| %>
  <div class="form_field">
    <%= f.label :date %><br>
    <%= f.date_field :date, class:'form_box' %>
    </div>

    <div class="form_field">
      <% dropdown = @restaurant.time_range(@restaurant) %>
      <% time_options = @restaurant.time_range_show(dropdown) %>
      <%= f.label :time %><br>
      <%= f.select :time, options_for_select(time_options, dropdown)%>
    </div>

    <div class="form_field">
      <%= f.label :party_size %> <br>
      <%= f.select :party_size, options_for_select((1..30),(1..30)) %>
    </div>
    <div class="form_field">
      <%= f.submit 'Find a Table', :class=>"form_button" %>
    </div>
  <% end %>
<% end %>

<h2 class="about_resto">About Restaurant : <span class="about_resto_name"><%=@restaurant.name%></span></h2>
<div class="about_resto_img">
  <%=image_tag(@restaurant.img_link, size: "600x600") %>
 </div>
<p class="about_resto_desc"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>

<% if session[:account_type] == 'admin' %>

<%= link_to 'Update Restaurant', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete Restaurant', @restaurant, method: :delete,  data: {confirm: "Are you sure you want to delete this restaurant"}  %>
<% end %>
</div>