config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/view'

  root 'restaurants#index'

  resources :sessions, only:[:create, :new, :destroy]
  resources :customers, except: [:index]
  resources :restaurants do #,only:[:show, :index] do
    resources :reservations
  end
  resources :categories
  # , only:[:index, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category  = Category.find(params[:id])
    @restaurants = Restaurant.where(category: @category.id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div>
  <h1> Search by Category </h1>
</div>
<% @categories.each do |category| %>

<% if false %>
  <div class="category">
    <div class="restaurant_image">
      <%= link_to image_tag(restaurant.img_link),restaurant_path(restaurant)%>
    </div>
<% end %>

    <p class="cat">
      <ul>
        <li> <%= link_to category.name, category_path(category) %></p> </li>
      </ul>
  </div>
<% end %>

app/views/categories/show.html.erb
  <% @restaurants.each do |restaurant| %>
    <div class="restaurant">
      <div class="restaurant_image">
        <%= link_to image_tag(restaurant.img_link),restaurant_path(restaurant)%>
      </div>
      <p class="restaurant_name"><%=restaurant.name%></p>
      <p class="restaurant_category"><%=restaurant.category.name%></p>
    </div>
  <% end %>