config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/view'

  root 'restaurants#index'

  resources :sessions, only:[:create, :new, :destroy]
  resources :customers, except: [:index]
  resources :restaurants do #,only:[:show, :index] do
    resources :reservations
  end
  resources :categories
  # , only:[:index, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header id="header">
    <div id="logo">
    <%= link_to 'SY', restaurants_path %>
  </div>
  <nav id="main-menu">
    <% if current_customer %>
    <div class="btn">  Hi, <%= current_customer.name%></div>

      <%= link_to 'Sign out', session_path(session[:customer_id]), method: :delete, class: "btn"%>

      <%= link_to 'View User Profile', customer_path(current_customer), class: "btn"%>

    <% else %>
    <div class="nav_link">
      <%= link_to 'Sign up', new_customer_path%>
    </div>

    <div class="nav_link">
      <%= link_to 'Log in', new_session_path%>
    </div>
    <% end %>
  </nav>
</header>

<div class='flash_notices'>
  <br>
<% if flash[:notice] %>
  <p id='notice'>
    <%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p id="alert"><%= flash[:alert] %></p>
  <% end %>
</div>

<%= yield %>

<footer id="footer">

  <ul class="footer_links">
    <li><a href="#">About Us</a></li>
    <li><a href="#">Careers</a></li>
    <li><a href="#">Blog</a></li>
    <li><a href="#">Contact Us</a></li>
  </ul>

  <div class="social_container">
    <h3 class="social_title"> Let's be Social</h3>
    <ul class="social">
      <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
      <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
    </ul>
  </div>
    <h2 class="copyright">&copy; Team Dmg Control</h2>
</footer>

</body>
</html>